// <auto-generated />
using System;
using JwtFlow.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JetFlow.Products.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205191836_v2.0.1")]
    partial class v201
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JwtFlow.Domain.BackOffice.Entities.ProductFlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal>("Price")
                        .HasColumnType("MONEY");

                    b.PrimitiveCollection<string>("UsersId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("JwtFlow.Domain.BackOffice.Entities.ProductFlight", b =>
                {
                    b.OwnsOne("JwtFlow.Domain.BackOffice.ObjectValue.FlightCity", "FlightCity", b1 =>
                        {
                            b1.Property<Guid>("ProductFlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CityOut")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CityStart")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("NVARCHAR")
                                .HasColumnName("CityStart");

                            b1.HasKey("ProductFlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("ProductFlightId");
                        });

                    b.OwnsOne("JwtFlow.Domain.BackOffice.ObjectValue.FlightDate", "FlightDate", b1 =>
                        {
                            b1.Property<Guid>("ProductFlightId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DateOut")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DateStart")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateStart");

                            b1.HasKey("ProductFlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("ProductFlightId");
                        });

                    b.Navigation("FlightCity")
                        .IsRequired();

                    b.Navigation("FlightDate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
